# extensions/attribix-pixel/shopify.extension.toml
# Save as UTF-8 (no BOM)

uid = "356f193c-8815-1a5d-666e-d9022b395b1d31aabf26"
type = "web_pixel_extension"

name = "Attribix Pixel"
handle = "attribix-pixel"
runtime_context = "strict"
main = "dist/main.js"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.accountID]
# IMPORTANT: name must match the key used in settings -> settings.accountID
name = "accountID"
description = "Account ID used by Attribix"
type = "single_line_text_field"
validations = [{ name = "min", value = "1" }]
