// app/routes/feeds.$shop.google[.xml].ts
// Public Google Shopping RSS feed at /feeds/{shop}/google.xml
// Submit this URL to Google Merchant Center.

import type { LoaderFunctionArgs } from "@remix-run/node";
import db from "~/db.server";

const APP_URL = process.env.SHOPIFY_APP_URL || "https://attribix-app.fly.dev";

function esc(str: string | null | undefined): string {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function loader({ params }: LoaderFunctionArgs) {
  const shop = params.shop as string;
  if (!shop) return new Response("Not found", { status: 404 });

  const anyDb = db as any;

  // Get feed config + products
  const config = await anyDb.productFeedConfig?.findUnique?.({ where: { shop } }).catch(() => null);
  const appendUtm = config?.appendUtm ?? true;
  const utmSource = config?.utmSource ?? "google_shopping";
  const utmMedium = config?.utmMedium ?? "cpc";

  const products: any[] = await anyDb.productFeedItem?.findMany?.({
    where: { shop },
    orderBy: { updatedAt: "desc" },
    take: 5000,
  }).catch(() => []) ?? [];

  const storeDomain = shop.replace(".myshopify.com", "");
  const storeUrl = `https://${shop}`;
  const now = new Date().toUTCString();

  const items = products.map((p) => {
    const variants: any[] = (() => { try { return JSON.parse(p.variantsJson || "[]"); } catch { return []; } })();
    const images: string[] = (() => { try { return JSON.parse(p.imagesJson || "[]"); } catch { return []; } })();
    const mainImage = images[0] ?? "";
    const additionalImages = images.slice(1, 11);

    // Use first variant for pricing
    const variant = variants[0];
    const price = variant?.price ?? p.price ?? "0.00";
    const comparePrice = variant?.compareAtPrice ?? p.compareAtPrice;
    const available = variant?.available ?? p.available ?? true;
    const variantId = variant?.id ?? "";
    const sku = variant?.sku ?? p.sku ?? "";
    const gtin = variant?.barcode ?? p.barcode ?? "";

    const utmSuffix = appendUtm ? `${variantId ? "&" : "?"}utm_source=${utmSource}&utm_medium=${utmMedium}&utm_campaign=product_feed` : "";
    const productUrl = `${storeUrl}/products/${p.handle}${variantId ? `?variant=${variantId}` : ""}${utmSuffix}`;

    // Custom labels
    const onSale = variant?.compareAtPrice && parseFloat(variant.compareAtPrice) > parseFloat(String(price));
    const customLabels = [
      onSale ? `<g:custom_label_0>sale</g:custom_label_0>` : "",
      gtin || sku ? "" : `<g:custom_label_3>no_gtin</g:custom_label_3>`,
    ].filter(Boolean).join("\n      ");

    return `    <item>
      <g:id>${esc(p.productId)}</g:id>
      <g:title>${esc(p.title)}</g:title>
      <g:description>${esc((p.bodyHtml ?? "").replace(/<[^>]*>/g, "").slice(0, 5000))}</g:description>
      <g:link>${esc(productUrl)}</g:link>
      <g:image_link>${esc(mainImage)}</g:image_link>
      ${additionalImages.map(img => `<g:additional_image_link>${esc(img)}</g:additional_image_link>`).join("\n      ")}
      <g:availability>${available ? "in_stock" : "out_of_stock"}</g:availability>
      <g:price>${esc(price)} ${esc(p.currency ?? "USD")}</g:price>
      ${comparePrice ? `<g:sale_price>${esc(price)} ${esc(p.currency ?? "USD")}</g:sale_price>` : ""}
      <g:brand>${esc(p.vendor ?? storeDomain)}</g:brand>
      <g:condition>new</g:condition>
      <g:product_type>${esc(p.productType ?? "")}</g:product_type>
      ${gtin ? `<g:gtin>${esc(gtin)}</g:gtin>` : ""}
      ${sku ? `<g:mpn>${esc(sku)}</g:mpn>` : ""}
      <g:identifier_exists>${gtin || sku ? "yes" : "no"}</g:identifier_exists>
      ${customLabels}
    </item>`;
  }).join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
  <channel>
    <title>${esc(storeDomain)} — Google Shopping Feed</title>
    <link>${esc(storeUrl)}</link>
    <description>Product feed generated by Attribix</description>
    <lastBuildDate>${now}</lastBuildDate>
${items}
  </channel>
</rss>`;

  return new Response(xml, {
    status: 200,
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
